graph LR
    subgraph "Peer-to-Peer"
    M1(( )) --- M2(( )) --- M3(( ))
    M4(( )) --- M5(( )) --- M6(( ))
    M1 --- M4
    M2 --- M5
    M3 --- M6

    style M1 fill:#3498db,stroke:#000,stroke-width:2px
    style M2 fill:#3498db,stroke:#000,stroke-width:2px
    style M3 fill:#3498db,stroke:#000,stroke-width:2px
    style M4 fill:#3498db,stroke:#000,stroke-width:2px
    style M5 fill:#3498db,stroke:#000,stroke-width:2px
    style M6 fill:#3498db,stroke:#000,stroke-width:2px
    end
