graph LR
    subgraph "Pipeline"
    P1(( )) --> P2(( )) --> P3(( )) --> P4(( ))

    style P1 fill:#3498db,stroke:#000,stroke-width:2px
    style P2 fill:#3498db,stroke:#000,stroke-width:2px
    style P3 fill:#3498db,stroke:#000,stroke-width:2px
    style P4 fill:#3498db,stroke:#000,stroke-width:2px
    end
